2022/09/22 12:41:18 - Terminal_Log - INFO      - log_save.py : 22 line - run the section pre_step
2022/09/22 12:41:18 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization
2022/09/22 12:41:18 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:41:18 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:19 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/imgs
2022/09/22 12:41:19 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:41:19 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:20 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/tools
2022/09/22 12:41:20 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:41:20 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:20 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/vt_sut_linux_tools
2022/09/22 12:41:20 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:41:20 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:21 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/virtualization_inband
2022/09/22 12:41:21 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:41:21 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:22 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/tools
2022/09/22 12:41:22 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:41:22 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:22 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; rm -rf /usr/bin/python; ln -s /usr/bin/python3.6 /usr/bin/python
2022/09/22 12:41:22 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:41:22 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:23 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; rm -rf /usr/bin/pip;ln -s /usr/bin/pip3.6 /usr/bin/pip
2022/09/22 12:41:23 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:41:23 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:24 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python -m pip install --upgrade pip
2022/09/22 12:41:25 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.3.1)
 

2022/09/22 12:41:25 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:41:25 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /etc/yum.repos.d/repos.bak; mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repos.bak
2022/09/22 12:41:26 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:41:26 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:26 - Terminal_Log - INFO      - log_save.py : 22 line - cp ../FILES/Centos-8.repo to /etc/yum.repos.d/Centos-8.repo
2022/09/22 12:41:27 - Terminal_Log - INFO      - log_save.py : 22 line - cp done

2022/09/22 12:41:27 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum update -y
2022/09/22 12:41:31 - Terminal_Log - INFO      - log_save.py : 22 line - out: CentOS-8 - Base                                 3.0 kB/s | 3.9 kB     00:01    
CentOS-8 - AppStream                            7.0 kB/s | 4.3 kB     00:00    
CentOS-8 Extra Packages - x86_64                4.8 kB/s | 4.7 kB     00:00    
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:31 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:32 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: yum remove qemu-kvm -y
2022/09/22 12:41:32 - Terminal_Log - INFO      - log_save.py : 22 line - out: No match for argument: qemu-kvm
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:32 - Terminal_Log - ERROR     - log_save.py : 28 line - err: No packages marked for removal.
 

2022/09/22 12:41:33 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install qemu-kvm -y
2022/09/22 12:41:43 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:03 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Dependencies resolved.
================================================================================================
 Package                  Arch    Version                                       Repo        Size
================================================================================================
Installing:
 qemu-kvm                 x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    AppStream  127 k
Installing dependencies:
 celt051                  x86_64  0.5.1.3-15.el8                                AppStream   63 k
 edk2-ovmf                noarch  20210527gite1999b264f1f-3.el8                 AppStream  3.6 M
 ipxe-roms-qemu           noarch  20181214-8.git133f4c47.el8                    AppStream  1.2 M
 libibumad                x86_64  35.0-1.el8                                    BaseOS      33 k
 libpmem                  x86_64  1.6.1-1.el8                                   AppStream   79 k
 qemu-kvm-block-curl      x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    AppStream  138 k
 qemu-kvm-block-gluster   x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    AppStream  139 k
 qemu-kvm-block-iscsi     x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    AppStream  145 k
 qemu-kvm-block-rbd       x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    AppStream  139 k
 qemu-kvm-block-ssh       x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    AppStream  140 k
 qemu-kvm-common          x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    AppStream  1.2 M
 qemu-kvm-core            x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    AppStream  3.5 M
 rdma-core                x86_64  35.0-1.el8                                    BaseOS      59 k
 seabios-bin              noarch  1.13.0-2.module_el8.5.0+746+bbd5d70c          AppStream  127 k
 seavgabios-bin           noarch  1.13.0-2.module_el8.5.0+746+bbd5d70c          AppStream   42 k
 sgabios-bin              noarch  1:0.20170427git-3.module_el8.5.0+746+bbd5d70c AppStream   13 k
 spice-server             x86_64  0.14.3-4.el8                                  AppStream  409 k

Transaction Summary
================================================================================================
Install  18 Packages

Total download size: 11 M
Installed size: 38 M
Downloading Packages:
(1/18): libibumad-35.0-1.el8.x86_64.rpm          26 kB/s |  33 kB     00:01    
(2/18): rdma-core-35.0-1.el8.x86_64.rpm          44 kB/s |  59 kB     00:01    
(3/18): celt051-0.5.1.3-15.el8.x86_64.rpm        47 kB/s |  63 kB     00:01    
(4/18): libpmem-1.6.1-1.el8.x86_64.rpm           79 kB/s |  79 kB     00:00    
(5/18): ipxe-roms-qemu-20181214-8.git133f4c47.e 1.0 MB/s | 1.2 MB     00:01    
(6/18): edk2-ovmf-20210527gite1999b264f1f-3.el8 2.2 MB/s | 3.6 MB     00:01    
(7/18): qemu-kvm-4.2.0-59.module_el8.5.0+1063+c 183 kB/s | 127 kB     00:00    
(8/18): qemu-kvm-block-curl-4.2.0-59.module_el8 176 kB/s | 138 kB     00:00    
(9/18): qemu-kvm-block-gluster-4.2.0-59.module_ 228 kB/s | 139 kB     00:00    
(10/18): qemu-kvm-block-iscsi-4.2.0-59.module_e 208 kB/s | 145 kB     00:00    
(11/18): qemu-kvm-block-rbd-4.2.0-59.module_el8 233 kB/s | 139 kB     00:00    
(12/18): qemu-kvm-block-ssh-4.2.0-59.module_el8 133 kB/s | 140 kB     00:01    
(13/18): qemu-kvm-common-4.2.0-59.module_el8.5. 1.0 MB/s | 1.2 MB     00:01    
(14/18): qemu-kvm-core-4.2.0-59.module_el8.5.0+ 2.3 MB/s | 3.5 MB     00:01    
(15/18): seabios-bin-1.13.0-2.module_el8.5.0+74 103 kB/s | 127 kB     00:01    
(16/18): seavgabios-bin-1.13.0-2.module_el8.5.0  43 kB/s |  42 kB     00:00    
(17/18): sgabios-bin-0.20170427git-3.module_el8  13 kB/s |  13 kB     00:01    
(18/18): spice-server-0.14.3-4.el8.x86_64.rpm   370 kB/s | 409 kB     00:01    
--------------------------------------------------------------------------------
Total                                           1.6 MB/s |  11 MB     00:06     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : qemu-kvm-common-15:4.2.0-59.module_el8.5.0+1063+c9    1/18 
  Running scriptlet: qemu-kvm-common-15:4.2.0-59.module_el8.5.0+1063+c9    1/18 
  Installing       : libpmem-1.6.1-1.el8.x86_64                            2/18 
  Running scriptlet: libpmem-1.6.1-1.el8.x86_64                            2/18 
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so is empty, not checked.

  Installing       : qemu-kvm-block-curl-15:4.2.0-59.module_el8.5.0+106    3/18 
  Installing       : qemu-kvm-block-gluster-15:4.2.0-59.module_el8.5.0+    4/18 
  Installing       : qemu-kvm-block-iscsi-15:4.2.0-59.module_el8.5.0+10    5/18 
  Installing       : qemu-kvm-block-rbd-15:4.2.0-59.module_el8.5.0+1063    6/18 
  Installing       : qemu-kvm-block-ssh-15:4.2.0-59.module_el8.5.0+1063    7/18 
  Installing       : sgabios-bin-1:0.20170427git-3.module_el8.5.0+746+b    8/18 
  Installing       : seavgabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70    9/18 
  Installing       : seabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70c.n   10/18 
  Installing       : ipxe-roms-qemu-20181214-8.git133f4c47.el8.noarch     11/18 
  Installing       : edk2-ovmf-20210527gite1999b264f1f-3.el8.noarch       12/18 
  Installing       : celt051-0.5.1.3-15.el8.x86_64                        13/18 
  Running scriptlet: celt051-0.5.1.3-15.el8.x86_64                        13/18 
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so is empty, not checked.

  Installing       : spice-server-0.14.3-4.el8.x86_64                     14/18 
  Installing       : rdma-core-35.0-1.el8.x86_64                          15/18 
  Running scriptlet: rdma-core-35.0-1.el8.x86_64                          15/18 
  Installing       : libibumad-35.0-1.el8.x86_64                          16/18 
  Running scriptlet: libibumad-35.0-1.el8.x86_64                          16/18 
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so is empty, not checked.

  Installing       : qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1063+c9b9   17/18 
  Running scriptlet: qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1063+c9b9   17/18 
  Installing       : qemu-kvm-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.   18/18 
  Running scriptlet: qemu-kvm-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.   18/18 
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so is empty, not checked.

  Verifying        : libibumad-35.0-1.el8.x86_64                           1/18 
  Verifying        : rdma-core-35.0-1.el8.x86_64                           2/18 
  Verifying        : celt051-0.5.1.3-15.el8.x86_64                         3/18 
  Verifying        : edk2-ovmf-20210527gite1999b264f1f-3.el8.noarch        4/18 
  Verifying        : ipxe-roms-qemu-20181214-8.git133f4c47.el8.noarch      5/18 
  Verifying        : libpmem-1.6.1-1.el8.x86_64                            6/18 
  Verifying        : qemu-kvm-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.    7/18 
  Verifying        : qemu-kvm-block-curl-15:4.2.0-59.module_el8.5.0+106    8/18 
  Verifying        : qemu-kvm-block-gluster-15:4.2.0-59.module_el8.5.0+    9/18 
  Verifying        : qemu-kvm-block-iscsi-15:4.2.0-59.module_el8.5.0+10   10/18 
  Verifying        : qemu-kvm-block-rbd-15:4.2.0-59.module_el8.5.0+1063   11/18 
  Verifying        : qemu-kvm-block-ssh-15:4.2.0-59.module_el8.5.0+1063   12/18 
  Verifying        : qemu-kvm-common-15:4.2.0-59.module_el8.5.0+1063+c9   13/18 
  Verifying        : qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1063+c9b9   14/18 
  Verifying        : seabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70c.n   15/18 
  Verifying        : seavgabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70   16/18 
  Verifying        : sgabios-bin-1:0.20170427git-3.module_el8.5.0+746+b   17/18 
  Verifying        : spice-server-0.14.3-4.el8.x86_64                     18/18 
Installed products updated.

Installed:
  celt051-0.5.1.3-15.el8.x86_64                                                 
  edk2-ovmf-20210527gite1999b264f1f-3.el8.noarch                                
  ipxe-roms-qemu-20181214-8.git133f4c47.el8.noarch                              
  libibumad-35.0-1.el8.x86_64                                                   
  libpmem-1.6.1-1.el8.x86_64                                                    
  qemu-kvm-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64                    
  qemu-kvm-block-curl-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64         
  qemu-kvm-block-gluster-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64      
  qemu-kvm-block-iscsi-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64        
  qemu-kvm-block-rbd-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64          
  qemu-kvm-block-ssh-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64          
  qemu-kvm-common-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64             
  qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64               
  rdma-core-35.0-1.el8.x86_64                                                   
  seabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70c.noarch                       
  seavgabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70c.noarch                    
  sgabios-bin-1:0.20170427git-3.module_el8.5.0+746+bbd5d70c.noarch              
  spice-server-0.14.3-4.el8.x86_64                                              

Complete!
 

2022/09/22 12:41:43 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:43 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install libvirt -y
2022/09/22 12:41:44 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:13 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package libvirt-8.0.0-6.module_el8.7.0+1140+ff0772f9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:44 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:45 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install python3-libvirt -y
2022/09/22 12:41:46 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:15 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package python3-libvirt-6.0.0-1.module_el8.5.0+746+bbd5d70c.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:46 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:46 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install virt-install -y
2022/09/22 12:41:47 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:16 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package virt-install-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:47 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:48 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install iperf -y
2022/09/22 12:41:49 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:17 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package iperf-2.1.6-2.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:49 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:49 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install wget -y
2022/09/22 12:41:50 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:19 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package wget-1.19.5-10.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:50 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:50 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install virt-manager -y
2022/09/22 12:41:51 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:20 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package virt-manager-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:51 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:52 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install tigervnc -y
2022/09/22 12:41:53 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:22 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package tigervnc-1.11.0-9.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:53 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:53 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install systemd-devel -y
2022/09/22 12:41:54 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:23 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:54 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:55 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install rpm-build autoconf automake libtool pkgconf rpmdevtools -y
2022/09/22 12:41:56 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:25 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package rpm-build-4.14.3-23.el8.x86_64 is already installed.
Package autoconf-2.69-29.el8.noarch is already installed.
Package automake-1.16.1-7.el8.noarch is already installed.
Package libtool-2.4.6-25.el8.x86_64 is already installed.
Package pkgconf-1.4.2-1.el8.x86_64 is already installed.
Package rpmdevtools-8.10-8.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:56 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:56 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install asciidoc xmlto libuuid-devel json-c-devel kmod-devel libudev-devel -y
2022/09/22 12:41:57 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:26 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package asciidoc-8.6.10-0.5.20180627gitf7c2274.el8.noarch is already installed.
No match for argument: kmod-devel
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
 

2022/09/22 12:41:57 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: kmod-devel
 

2022/09/22 12:41:57 - Terminal_Log - INFO      - log_save.py : 22 line - run the section python_env_step
2022/09/22 12:41:58 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install gcc-c++ -y
2022/09/22 12:41:59 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:28 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package gcc-c++-8.5.0-13.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:41:59 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:41:59 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install rust -y
2022/09/22 12:42:00 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:29 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package rust-1.54.0-3.module_el8.5.0+1023+0c63d3d6.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:42:00 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:42:01 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install python36-devel -y
2022/09/22 12:42:02 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:30 ago on Thu 22 Sep 2022 03:10:41 AM IST.
Package python36-devel-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:42:02 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:42:02 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install xmltodict  -i https://pypi.org/simple--user
2022/09/22 12:42:03 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: xmltodict in /usr/local/lib/python3.6/site-packages (0.13.0)
 

2022/09/22 12:42:03 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:03 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install wcwidth  -i https://pypi.org/simple--user
2022/09/22 12:42:04 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (0.2.5)
 

2022/09/22 12:42:04 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:04 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pathlib2  -i https://pypi.org/simple--user
2022/09/22 12:42:05 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: pathlib2 in /usr/local/lib/python3.6/site-packages (2.3.7.post1)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from pathlib2) (1.11.0)
 

2022/09/22 12:42:05 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:05 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install artifactory  -i https://pypi.org/simple--user
2022/09/22 12:42:06 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: artifactory in /usr/local/lib/python3.6/site-packages (0.1.17)
Requirement already satisfied: pathlib in /usr/local/lib/python3.6/site-packages (from artifactory) (1.0.1)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from artifactory) (2.20.0)
Requirement already satisfied: python-dateutil in /usr/lib/python3.6/site-packages (from artifactory) (2.6.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil->artifactory) (1.11.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->artifactory) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3.6/site-packages (from requests->artifactory) (2.5)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->artifactory) (1.24.2)
 

2022/09/22 12:42:06 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:06 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install anybadge  -i https://pypi.org/simple--user
2022/09/22 12:42:07 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: anybadge in /usr/local/lib/python3.6/site-packages (1.9.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from anybadge) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->anybadge) (3.0.9)
 

2022/09/22 12:42:07 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:07 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pyqt5  -i https://pypi.org/simple--user
2022/09/22 12:42:08 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: pyqt5 in /usr/local/lib64/python3.6/site-packages (5.15.6)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (12.9.1)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (5.15.2)
 

2022/09/22 12:42:08 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:09 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pywin32  -i https://pypi.org/simple--user
2022/09/22 12:42:10 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
 

2022/09/22 12:42:10 - Terminal_Log - ERROR     - log_save.py : 28 line - err: ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
 

2022/09/22 12:42:11 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install prettytable  -i https://pypi.org/simple--user
2022/09/22 12:42:11 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: prettytable in /usr/local/lib/python3.6/site-packages (2.5.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/site-packages (from prettytable) (4.8.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from prettytable) (0.2.5)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (3.6.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (4.1.1)
 

2022/09/22 12:42:11 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:12 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install bcrypt  -i https://pypi.org/simple--user
2022/09/22 12:42:12 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: bcrypt in /usr/local/lib64/python3.6/site-packages (4.0.0)
 

2022/09/22 12:42:12 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:13 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install setuptools_rust  -i https://pypi.org/simple--user
2022/09/22 12:42:13 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: setuptools_rust in /usr/local/lib/python3.6/site-packages (1.1.2)
Requirement already satisfied: setuptools>=46.1 in /usr/local/lib/python3.6/site-packages (from setuptools_rust) (59.6.0)
Requirement already satisfied: semantic-version<3,>=2.8.2 in /usr/local/lib/python3.6/site-packages (from setuptools_rust) (2.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.6/site-packages (from setuptools_rust) (4.1.1)
 

2022/09/22 12:42:13 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:14 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install cffi  -i https://pypi.org/simple--user
2022/09/22 12:42:15 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: cffi in /usr/local/lib64/python3.6/site-packages (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi) (2.21)
 

2022/09/22 12:42:15 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:15 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install cryptography==3.2.1  -i https://pypi.org/simple--user
2022/09/22 12:42:17 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
 

2022/09/22 12:42:17 - Terminal_Log - ERROR     - log_save.py : 28 line - err: ERROR: Could not find a version that satisfies the requirement cryptography==3.2.1 (from versions: none)
ERROR: No matching distribution found for cryptography==3.2.1
 

2022/09/22 12:42:17 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install prettytable  -i https://pypi.org/simple--user
2022/09/22 12:42:18 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: prettytable in /usr/local/lib/python3.6/site-packages (2.5.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from prettytable) (0.2.5)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/site-packages (from prettytable) (4.8.3)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (3.6.0)
 

2022/09/22 12:42:18 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:18 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pynacl  -i https://pypi.org/simple--user
2022/09/22 12:42:19 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: pynacl in /usr/local/lib64/python3.6/site-packages/PyNaCl-1.5.0-py3.6-linux-x86_64.egg (1.5.0)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib64/python3.6/site-packages (from pynacl) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.4.1->pynacl) (2.21)
 

2022/09/22 12:42:19 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:19 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install paramiko  -i https://pypi.org/simple--user
2022/09/22 12:42:20 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: paramiko in /usr/local/lib/python3.6/site-packages (2.11.0)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from paramiko) (1.11.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib64/python3.6/site-packages (from paramiko) (38.0.1)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib64/python3.6/site-packages/PyNaCl-1.5.0-py3.6-linux-x86_64.egg (from paramiko) (1.5.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib64/python3.6/site-packages (from paramiko) (4.0.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography>=2.5->paramiko) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=2.5->paramiko) (2.21)
 

2022/09/22 12:42:20 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:21 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install scp  -i https://pypi.org/simple--user
2022/09/22 12:42:21 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: scp in /usr/local/lib/python3.6/site-packages (0.14.4)
Requirement already satisfied: paramiko in /usr/local/lib/python3.6/site-packages (from scp) (2.11.0)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from paramiko->scp) (1.11.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib64/python3.6/site-packages (from paramiko->scp) (4.0.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib64/python3.6/site-packages/PyNaCl-1.5.0-py3.6-linux-x86_64.egg (from paramiko->scp) (1.5.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib64/python3.6/site-packages (from paramiko->scp) (38.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography>=2.5->paramiko->scp) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=2.5->paramiko->scp) (2.21)
 

2022/09/22 12:42:21 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:42:21 - Terminal_Log - INFO      - log_save.py : 22 line - run the section auto_env_step
2022/09/22 12:42:22 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; wget -i /root/auto_set_env/sut_linux_tools.txt --no-check-certificate -P /home/BKCPkg/tools --page-requisites --no-host-directories --cut-dirs=1000 URL
2022/09/22 12:42:27 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:42:27 - Terminal_Log - ERROR     - log_save.py : 28 line - err: --2022-09-22 03:11:32--  http://url/
Resolving proxy-iind.intel.com (proxy-iind.intel.com)... 10.224.224.80
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy request sent, awaiting response... 503 Service Unavailable
2022-09-22 03:11:33 ERROR 503: Service Unavailable.

--2022-09-22 03:11:33--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/7.0_xmlcli_windows_linux_esxi_Python2&3_ipclean.zip
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:33--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/devchk.zip
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:33--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/ipmitool-1.8.18-14.el8.x86_64.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:33--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/OpenIPMI-2.0.27-1.el8.x86_64.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:34--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/Python-3.6.8.tgz
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:34--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/Python-3.8.8.tgz
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:34--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python3-pip-9.0.3-16.el8.noarch.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:34--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python3-setuptools-39.2.0-5.el8.noarch.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:34--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:35--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python3-libs-3.6.8-37.el8.x86_64.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:35--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python3-pip-wheel-9.0.3-20.el8.noarch.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:35--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python3-setuptools-wheel-39.2.0-6.el8.noarch.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:35--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python38-3.8.8-4.module_el8.5.0+896+eb9e77ba.x86_64.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:35--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python38-pip-19.3.1-4.module_el8.5.0+896+eb9e77ba.noarch.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:36--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python38-setuptools-41.6.0-5.module_el8.5.0+896+eb9e77ba.noarch.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:36--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/python38-libs-3.8.8-4.module_el8.5.0+896+eb9e77ba.x86_64.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:36--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/screen-4.6.2-10.el8.x86_64.rpm
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:36--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/set_toolkit_src_root.py
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:36--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/XmlCliKnobs.efi
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:37--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/cmdtool_wht.efi
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:37--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/cmdtool_egs.efi
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
--2022-09-22 03:11:37--  https://ubit-artifactory-sh.intel.com/artifactory/validationtools-sh-local/env/sut/linux/set_toolkit_src_root.py
Connecting to proxy-iind.intel.com (proxy-iind.intel.com)|10.224.224.80|:911... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
 

2022/09/22 12:42:28 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /opt/APP; rm -rf /opt/APP/xmlcli
2022/09/22 12:42:28 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:42:28 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:42:28 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; cd /home/BKCPkg/tools; xmlcli_zip=`ls | grep xmlcli`;unzip $xmlcli_zip ; /usr/bin/cp -rf xmlcli /opt/APP
2022/09/22 12:42:28 - Terminal_Log - INFO      - log_save.py : 22 line - out: Archive:  7.0_xmlcli_windows_linux_esxi_Python2&3_ipclean.zip
 

2022/09/22 12:42:28 - Terminal_Log - ERROR     - log_save.py : 28 line - err: caution: filename not matched:  xmlcli
 

