2022/09/22 12:18:41 - Terminal_Log - INFO      - log_save.py : 22 line - run the section pre_step
2022/09/22 12:18:42 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization
2022/09/22 12:18:42 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:18:42 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:18:43 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/imgs
2022/09/22 12:18:43 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:18:43 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:18:43 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/tools
2022/09/22 12:18:43 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:18:43 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:18:44 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/vt_sut_linux_tools
2022/09/22 12:18:44 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:18:44 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:18:45 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/virtualization_inband
2022/09/22 12:18:45 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:18:45 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:18:45 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  rm -rf /usr/bin/python; ln -s /usr/bin/python3.6 /usr/bin/python
2022/09/22 12:18:46 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:18:46 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:18:46 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  rm -rf /usr/bin/pip;ln -s /usr/bin/pip3.6 /usr/bin/pip
2022/09/22 12:18:46 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:18:46 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:18:47 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python -m pip install --upgrade pip
2022/09/22 12:18:48 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.3.1)
 

2022/09/22 12:18:48 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:18:49 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /etc/yum.repos.d/repos.bak; mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repos.bak
2022/09/22 12:18:49 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:18:49 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:18:50 - Terminal_Log - INFO      - log_save.py : 22 line - cp ../FILES/Centos-8.repo to /etc/yum.repos.d/Centos-8.repo
2022/09/22 12:18:50 - Terminal_Log - INFO      - log_save.py : 22 line - cp done

2022/09/22 12:18:50 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum update -y
2022/09/22 12:18:54 - Terminal_Log - INFO      - log_save.py : 22 line - out: CentOS-8 - Base                                 3.0 kB/s | 3.9 kB     00:01    
CentOS-8 - AppStream                            7.7 kB/s | 4.3 kB     00:00    
CentOS-8 Extra Packages - x86_64                4.3 kB/s | 4.7 kB     00:01    
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:18:54 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:18:55 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum remove export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; qemu-kvm -y
2022/09/22 12:18:56 - Terminal_Log - INFO      - log_save.py : 22 line - out: No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:18:56 - Terminal_Log - ERROR     - log_save.py : 28 line - err: No packages marked for removal.
bash: qemu-kvm: command not found
 

2022/09/22 12:18:56 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; libvirt -y
2022/09/22 12:18:57 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:03 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:18:57 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: libvirt: command not found
 

2022/09/22 12:18:58 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python3-libvirt -y
2022/09/22 12:18:58 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:04 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:18:58 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: python3-libvirt: command not found
 

2022/09/22 12:18:59 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;virt-install -y
2022/09/22 12:19:00 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:06 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:00 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: -y
 

2022/09/22 12:19:00 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;iperf -y
2022/09/22 12:19:01 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:07 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:01 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
iperf: option requires an argument -- y
Usage: iperf [-s|-c host] [options]
Try `iperf --help' for more information.
 

2022/09/22 12:19:02 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;wget -y
2022/09/22 12:19:03 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:09 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:03 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
wget: invalid option -- 'y'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
 

2022/09/22 12:19:03 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;virt-manager -y
2022/09/22 12:19:04 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:10 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:04 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(virt-manager:44165): Gtk-WARNING **: 02:48:15.062: cannot open display: 
 

2022/09/22 12:19:05 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;tigervnc -y
2022/09/22 12:19:06 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:12 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:06 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: tigervnc: command not found
 

2022/09/22 12:19:06 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;systemd-devel -y
2022/09/22 12:19:07 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:13 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:07 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: systemd-devel: command not found
 

2022/09/22 12:19:08 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;rpm-build autoconf automake libtool pkgconf rpmdevtools -y
2022/09/22 12:19:09 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:15 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:09 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: rpm-build: command not found
 

2022/09/22 12:19:09 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;asciidoc xmlto libuuid-devel json-c-devel kmod-devel libudev-devel -y
2022/09/22 12:19:10 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:16 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:10 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
asciidoc: Too many arguments

Man page:     asciidoc --help manpage
Syntax:       asciidoc --help syntax
 

2022/09/22 12:19:10 - Terminal_Log - INFO      - log_save.py : 22 line - run the section python_env_step
2022/09/22 12:19:11 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;gcc-c++ -y
2022/09/22 12:19:12 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:18 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:12 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: gcc-c++: command not found
 

2022/09/22 12:19:12 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;rust -y
2022/09/22 12:19:13 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:19 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:13 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: rust: command not found
 

2022/09/22 12:19:14 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;python36-devel -y
2022/09/22 12:19:15 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:21 ago on Thu 22 Sep 2022 02:48:04 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:19:15 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: python36-devel: command not found
 

2022/09/22 12:19:15 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install xmltodict  
2022/09/22 12:19:15 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:15 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install xmltodict  '
 

2022/09/22 12:19:16 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install wcwidth  
2022/09/22 12:19:16 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:16 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install wcwidth  '
 

2022/09/22 12:19:17 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install pathlib2  
2022/09/22 12:19:17 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:17 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install pathlib2  '
 

2022/09/22 12:19:17 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install artifactory  
2022/09/22 12:19:17 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:17 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install artifactory  '
 

2022/09/22 12:19:18 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install anybadge  
2022/09/22 12:19:18 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:18 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install anybadge  '
 

2022/09/22 12:19:19 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install pyqt5  
2022/09/22 12:19:19 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:19 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install pyqt5  '
 

2022/09/22 12:19:19 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install pywin32  
2022/09/22 12:19:20 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:20 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install pywin32  '
 

2022/09/22 12:19:20 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install prettytable  
2022/09/22 12:19:20 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:20 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install prettytable  '
 

2022/09/22 12:19:21 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install bcrypt  
2022/09/22 12:19:21 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:21 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install bcrypt  '
 

2022/09/22 12:19:21 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install setuptools_rust  
2022/09/22 12:19:22 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:22 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install setuptools_rust  '
 

2022/09/22 12:19:22 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install cffi  
2022/09/22 12:19:22 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:22 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install cffi  '
 

2022/09/22 12:19:23 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install cryptography  
2022/09/22 12:19:23 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:23 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install cryptography  '
 

2022/09/22 12:19:23 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install prettytable  
2022/09/22 12:19:24 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:24 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install prettytable  '
 

2022/09/22 12:19:24 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install pynacl  
2022/09/22 12:19:24 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:24 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install pynacl  '
 

2022/09/22 12:19:25 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install paramiko  
2022/09/22 12:19:25 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:25 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install paramiko  '
 

2022/09/22 12:19:26 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install scp  
2022/09/22 12:19:26 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:19:26 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install scp  '
 

